### ISSUE TITLE
Usage on the server side?

### ISSUE THREAD

**Issue by ricardograca** [helpers/handlebars-helper-md#2]
How can this be used on the server? I tried the obvious:

```
var md = require('handlebars-helper-md')
handlebars.registerHelper(md)
```

but it didn't work:

> TypeError: Object #<Object> has no method 'call'

**Comment by jonschlinkert** [comment]
@doowb any thoughts on this?

**Comment by doowb** [comment]
This helper is built to work with assemble 0.4.x.

It's not really setup to work outside of assemble 0.4.x since it uses `assemble.partials` and `grunt` internally. What are you trying to accomplish with this helper? There's probably a better one that doesn't use assemble 0.4.x directly.

**Comment by jonschlinkert** [comment]
this one https://github.com/helpers/helper-md

**Comment by ricardograca** [comment]
Thank you for your answers and sorry for the confusion.

I didn't realize this was for Assemble only since the title seems to indicate it's for Handlebars and it's the first package that comes up on Google when searching for "Handlebars helper markdown" and the Readme doesn't specify that it requires Assemble.
